### ISSUE TITLE
NONAT-T10-R031 Tax categories MUST match provided tax categories on document level.

### ISSUE THREAD

**Issue by ismail-majid** [difi/vefa-ehf-postaward#257] opened 2018-01-17 09:37 UTC
Please make sure this box is checked before submitting your issue - thank you!

- [ ] Issue is related to guides or validation part of EHF in post-award.

Issues related to PEPPOL BIS or rules part of PEPPOL BIS must be sent to rfc@peppol.eu.

Your issue here: I am getting the error for EHF Invoice using https://vefa.difi.no/validator/  but the schematron is not throwing an error using the same file.

I am using the schematron available at https://github.com/difi/vefa-ehf-postaward/tree/master/rules/ehf-invoice-2.0/sch

Kindly provide the scehmatron used by the validator at https://vefa.difi.no/validator/ 

Thank You.

Best Regards,

Majid

**Comment by klakegg** [comment] 2018-01-19 11:36
Duplicate of #255

**Closed by klakegg** 2018-01-19 11:36 UTC
