### ISSUE TITLE
Unsupported attachment type visibility on online VEFA validator - Error Or Warning 

### ISSUE THREAD

**Issue by saurabhsharma-bw** [difi/vefa-ehf-postaward#236] opened 2017-10-04 09:52 UTC
Please make sure this box is checked before submitting your issue - thank you!

- [X] Issue is related to guides or validation part of EHF in post-award.

Issues related to PEPPOL BIS or rules part of PEPPOL BIS must be sent to rfc@peppol.eu.

Your issue here:

https://github.com/difi/vefa-ehf-postaward/commit/ca0acaba7b36740fb81b399039c6ca640f48f8a8 says that "Add warning if mimetype other than recommended types" and currently we do not support office 2013 document types as attachments as per - https://github.com/difi/vefa-ehf-postaward/issues/42 and https://github.com/difi/vefa-ehf-postaward/issues/221

From the above discussions i see that the required support can take time / more discussions.
 What i am concerned about is that currently if an unsupported attachments comes then if we validate on online VEFA validator, it returns an error
![image](https://user-images.githubusercontent.com/32509102/31169875-bd324ada-a917-11e7-8d66-ee0a5b1623d2.png)

Shouldn't it be Warning as per above post #42? is this something that got changed - from WARN -->>Error in any previous releases we had?

**Comment by klakegg** [comment] 2017-10-04 13:54
Duplicate of #42.

**Closed by klakegg** 2017-10-04 13:54 UTC

**Comment by saurabhsharma-bw** [comment] 2017-10-05 04:48
i understand, this topic of unsupported attachment types is duplicate of https://github.com/difi/vefa-ehf-postaward/issues/42.

But i was seeking a reply for what reason it returns ERROR and not WARNING during online VEFA validation.
as per the post https://github.com/difi/vefa-ehf-postaward/issues/42 it should return WARINING.
has the rule changed from Warning to Error in recent times? or is this correct behavior
