### ISSUE TITLE
EHF Invoice and CreditNote Schematron

### ISSUE THREAD

**Issue by ismail-majid** [difi/vefa-ehf-postaward#256] opened 2018-01-16 12:49 UTC
Please make sure this box is checked before submitting your issue - thank you!

- [ ] Issue is related to guides or validation part of EHF in post-award.

Issues related to PEPPOL BIS or rules part of PEPPOL BIS must be sent to rfc@peppol.eu.

Your issue here:
I have tried the availble schematron available at this repository for EHF Inoivce but its still making the document valid. Can I share the document?

https://github.com/difi/vefa-ehf-postaward/tree/master/rules/ehf-invoice-2.0/sch

The issue is already reported 
https://github.com/difi/vefa-ehf-postaward/issues/255 but gets closed so it will be great if someone can share the latest Schematron for the invoice and credit note or validate the test file I am using and failing at https://vefa.difi.no/validator/

**Comment by ismail-majid** [comment] 2018-01-19 10:06
@klakegg  The Schematron available at https://github.com/difi/vefa-ehf-postaward/tree/master/rules/ehf-invoice-2.0/sch are xsl 2.0 compatible. Can you share xls 1.0 compliant Schematron

**Comment by klakegg** [comment] 2018-01-19 11:35
This is duplicate of #255.

The files are ISO Schematron with XSLT 2 compliant. XSLT 2 is required according to OpenPEPPOL.

**Closed by klakegg** 2018-01-19 11:35 UTC
